# Generated by Django 5.2.8 on 2025-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Секунды (максимум 120)",
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Дни (максимум 7)",
                verbose_name="Периодичность (в днях)",
            ),
        ),
    ]
